language: ruby
rvm:
- ruby-head
- jruby-head
- 2.1.1
- 2.0.0
- 1.9.3
- 1.9.2
- jruby-19mode
- jruby-18mode
- rbx-2.1.1
- rbx-2.0.0
- 1.8.7
matrix:
  allow_failures:
    - rvm: rbx-2.1.1
    - rvm: rbx-2.0.0
    - rvm: 1.8.7
    - rvm: jruby-head
    - rvm: jruby-18mode
